const PROJETS = [
  {
    id: 1,
    num: '01',
    thumb: 'Sources/projets/transport luxe/Frame 35422729.png',
    titreCourt: 'Refonte d\'un parcours',
    sousTitreCourt: 'Optimisation du recrutement de partenaires pour une entreprise de transport de luxe',
    clientCourt: 'Transport de luxe',
    highlight: 'qualification',
    dureeCourte: '12 mois',
    kpis: [
      { titre: '90%', desc: 'Taux d\'occupation des véhicules de formation, contre 50 % auparavant' },
      { titre: '1 mois', desc: 'Délai de traitement d\'un dossier, de la création de compte à la signature du contrat' },
      { titre: 'Optimisé', desc: 'Taux de traitement des dossiers grâce à l\'optimisation des créneaux d\'entretien' },
    ],
    titre: 'Refonte du parcours d\'acquisition & qualification de partenaires',
    sousTitre: 'Optimisation du recrutement de partenaires pour une entreprise de transport de luxe',
    client: 'Entreprise de transport de luxe (secteur premium)',
    annee: '2025',
    type: 'Conception d\'une plateforme web dédiée — parcours d\'inscription et back-office de qualification',
    role: 'Product Designer (UX Research, UI Design, collaboration tech & PO)',
    duree: '12 mois — 7 mois de cadrage/conception + 5 mois de développement (10 sprints)',
    equipe: '1 Lead UX-UI · 1 UX · 1 UI · 1 PO · 1 Scrum Master · 2 Devs',
    outils: ['Mural', 'Figma', 'Loop'],
    statut: 'Confidentiel',
    competences: ['UX Research', 'Design System', 'Mobile-first', 'Prototypage', 'Éco-conception', 'Collaboration Agile', 'Accompagnement PO'],
    contexte: 'Le client souhaitait élargir sa flotte en recrutant de nouveaux partenaires de qualité, sans recourir à une plateforme ouverte comme ses concurrents. Le processus de qualification, entièrement manuel (mails, téléphone, vérifications documentaires), mobilisait fortement les équipes internes réparties en France et à l\'international, avec des critères hétérogènes selon les agences. Objectifs : fluidifier le travail des équipes de qualification, réduire les délais d\'inscription et adresser une cible en mobilité (mobile-first).',
    demarche: [
      { titre: 'Cadrage', desc: 'Définition des objectifs, ateliers de priorisation, choix techniques et interopérabilité avec l\'écosystème client, principes d\'éco-conception.' },
      { titre: 'Recherche utilisateur', desc: 'Interviews terrain avec le service partenaires et des chauffeurs, révélant les principales frustrations : vérification documentaire chronophage, gestion par mail, RDV de formation non honorés, disparité des process entre agences. En parallèle, benchmark concurrentiel détaillé des parcours de création de compte des grandes plateformes de VTC, avec comparaison des positionnements.' },
      { titre: 'Conception', desc: 'Pré-conception en HTML assistée par IA pour stabiliser vite les parcours, conception du design system en parallèle via Storybook, allers-retours de validation avec le client, puis maquettes finalisées sur Figma en mobile-first et passation aux développeurs.' },
      { titre: 'Accompagnement PO', desc: 'Co-rédaction du backlog, ateliers de priorisation MVP, découpage en 6 sprints (création de compte, qualification entreprise / chauffeurs / véhicules, entretiens, dashboard, gestion documentaire).' },
      { titre: 'Phase dev', desc: 'Validation des écrans à chaque sprint, itérations selon les contraintes techniques, échanges continus avec le lead tech.' },
    ],
    defis: [
      { titre: 'Méthodologie user-centric remise en question côté client', desc: 'Le MOA souhaitait écarter entretiens et ateliers pour imposer sa vision produit.', solution: 'Restructuration du planning et accompagnement du chef de projet pour impliquer les utilisateurs sous sa supervision : co-animation des entretiens et ateliers communs.' },
      { titre: 'Risque de ne pas atteindre l\'objectif d\'automatisation', desc: 'Le prestataire de vérification documentaire ne couvrait pas tous les besoins.', solution: 'Proposition d\'intégrer le pôle IA interne pour la vérification de conformité documentaire, validée en atelier technique après 4 mois de recherche.' },
      { titre: 'Aucune documentation héritée des projets précédents', desc: 'Deux projets antérieurs avaient été menés avec d\'autres équipes, sans design system ni guidelines.', solution: 'Création des fondations d\'un design system en m\'appuyant sur les projets existants et en collaboration avec le lead front, validé ensuite par le client sur les principes graphiques clés.' },
    ],
    resultats: [
      'Taux d\'occupation des véhicules de formation porté à 90 % (vs 50 % auparavant)',
      'Délai de traitement d\'un dossier ramené à 1 mois (de la création de compte à la signature du contrat)',
      'Augmentation du taux de traitement des dossiers grâce à l\'optimisation des créneaux d\'entretien',
    ],
    images: [
      // Les deux visuels paysage d'abord, puis la planche des écrans mobiles.
      {
        type: 'animated',
        alt: 'Parcours de création de compte', altEn: 'Account creation journey',
        w: 918, h: 506,
        frames: [
          'Sources/projets/refonte%20parcours/animation/1.png',
          'Sources/projets/refonte%20parcours/animation/2.png',
          'Sources/projets/refonte%20parcours/animation/3.png',
          'Sources/projets/refonte%20parcours/animation/4.png',
        ],
      },
      { src: 'Sources/projets/refonte%20parcours/criteres.png', w: 899, h: 590, type: 'desktop', alt: 'Critères de qualification', altEn: 'Qualification criteria' },
      { src: 'Sources/projets/refonte%20parcours/S6%20%E2%80%94%20Mon%20entreprise.png', w: 393, h: 1117, span: 'narrow', type: 'mobile', alt: 'Tableau de bord partenaire', altEn: 'Partner dashboard' },
      { src: 'Sources/annexe-book/chabe-1.jpg', w: 402, h: 874, span: 'narrow', type: 'mobile', alt: 'Création de compte partenaire', altEn: 'Partner account creation' },
      { src: 'Sources/annexe-book/chabe-2.jpg', w: 402, h: 874, span: 'narrow', type: 'mobile', alt: 'Qualification — informations entreprise', altEn: 'Qualification — company details' },
      { src: 'Sources/annexe-book/chabe-3.jpg', w: 402, h: 874, span: 'narrow', type: 'mobile', alt: 'Qualification — déclaration des véhicules', altEn: 'Qualification — vehicle declaration' },
      { src: 'Sources/annexe-book/chabe-4.jpg', w: 402, h: 874, span: 'narrow', type: 'mobile', alt: 'Fin de qualification et programmation des entretiens', altEn: 'End of qualification and interview scheduling' },
      { src: 'Sources/annexe-book/chabe-5.jpg', w: 402, h: 874, span: 'narrow', type: 'mobile', alt: 'Tableau de bord partenaire — suivi de la progression', altEn: 'Partner dashboard — progress tracking' },
    ],
    en: {
      titreCourt: 'Journey redesign',
      clientCourt: 'Luxury transport',
      sousTitreCourt: 'Optimising partner recruitment for a luxury transport company',
      titre: 'Redesign of the partner acquisition & qualification journey',
      highlight: 'qualification',
      type: 'Web platform design — registration journey and qualification back-office',
      role: 'Product Designer (UX Research, UI Design, tech & PO collaboration)',
      dureeCourte: '12 months',
      statut: 'Confidential',
      contexte: 'The client wanted to expand their fleet by recruiting quality partners, without resorting to an open platform like their competitors. The qualification process, entirely manual (emails, phone calls, document checks), placed a heavy burden on internal teams spread across France and internationally, with inconsistent criteria between agencies. Objectives: streamline the work of qualification teams, reduce registration times, and address a mobile-first target audience.',
      demarche: [
        { titre: 'Scoping', desc: 'Defining objectives, prioritisation workshops, technical choices and interoperability with the client ecosystem, eco-design principles.' },
        { titre: 'User research', desc: 'Field interviews with the partner team and with drivers, revealing the main frustrations: time-consuming document verification, email-based management, missed training appointments, inconsistent processes between agencies. In parallel, a detailed competitive benchmark of the sign-up journeys of the major ride-hailing platforms, comparing their positioning.' },
        { titre: 'Design', desc: 'AI-assisted HTML pre-design to stabilise the journeys quickly, design system built in parallel via Storybook, validation rounds with the client, then final mobile-first designs in Figma and developer handoff.' },
        { titre: 'PO support', desc: 'Co-writing the backlog, MVP prioritisation workshops, breakdown into 6 sprints (account creation, company/driver/vehicle qualification, interviews, dashboard, document management).' },
        { titre: 'Dev phase', desc: 'Screen validation at each sprint, iterations based on technical constraints, ongoing exchanges with the tech lead.' },
      ],
      defis: [
        { titre: 'User-centric methodology challenged by the client', desc: 'The project owner wanted to bypass interviews and workshops to impose their own product vision.', solution: 'Restructured the schedule and coached the project manager to involve users under their supervision: co-facilitation of interviews and joint workshops.' },
        { titre: 'Risk of not achieving the automation objective', desc: 'The document verification provider did not cover all needs.', solution: 'Proposed integrating the internal AI team for document compliance verification, validated in a technical workshop after 4 months of research.' },
        { titre: 'No documentation from previous projects', desc: 'Two prior projects had been carried out by other teams, with no design system or guidelines.', solution: 'Created design system foundations based on existing projects and in collaboration with the front-end lead, subsequently validated by the client on key graphic principles.' },
      ],
      resultats: [
        'Training vehicle occupancy rate brought to 90% (vs 50% previously)',
        'File processing time reduced to 1 month (from account creation to contract signing)',
        'Increased file processing rate through optimised interview slot management',
      ],
      kpis: [
        { titre: '90%', desc: 'Training vehicle occupancy rate, vs 50% previously' },
        { titre: '1 month', desc: 'File processing time, from account creation to contract signing' },
        { titre: 'Optimised', desc: 'Increased file processing rate thanks to optimised interview slot management' },
      ],
      competences: ['UX Research', 'Design System', 'Mobile-first', 'Prototyping', 'Eco-design', 'Agile Collaboration', 'PO Support'],
    },
  },

  {
    id: 2,
    num: '02',
    thumb: 'Sources/preview aéronautic.png',
    titreCourt: 'Aéronautique & IA',
    sousTitreCourt: 'Aider les compagnies aériennes à diagnostiquer et réparer leurs pièces plus rapidement grâce à l\'IA',
    clientCourt: 'Constructeur aéronautique',
    highlight: 'détection',
    dureeCourte: '6 mois',
    kpis: [
      { titre: '190 K€', desc: 'Investissement débloqué pour poursuivre le projet et concevoir l\'ensemble des parcours' },
      { titre: 'POC validé', desc: 'Démonstration du potentiel financier du produit au client' },
      { titre: 'Phase 2', desc: 'Industrialisation de l\'outil planifiée à l\'issue du développement complet' },
    ],
    titre: 'POC d\'un outil de détection de dommages assisté par IA',
    sousTitre: 'Aider les compagnies aériennes à diagnostiquer et réparer leurs pièces plus rapidement grâce à l\'IA',
    client: 'Constructeur aéronautique',
    annee: '2025',
    type: 'Proof of Concept (POC) — outil métier intégrant IA et reconnaissance d\'image',
    role: 'Product Designer (UX Research, UI Design, collaboration avec l\'équipe IA)',
    duree: '6 mois',
    equipe: '1 Lead UX-UI · 1 UX · 1 UI · 1 PO · 1 Développeur IA',
    outils: ['Figma', 'Mural'],
    statut: 'Confidentiel',
    competences: ['UX Research', 'IA & Design', 'Co-conception', 'Prototypage haute fidélité', 'Design responsable', 'Collaboration multidisciplinaire'],
    objectifs: [
      'Réduire le temps de stationnement au sol des avions',
      'Faciliter le diagnostic dès la détection par le client',
      'Améliorer le référentiel de réparation existant',
    ],
    contexte: 'Acteur majeur de la construction aéronautique, le client dispose d\'un référentiel riche de plusieurs milliers de cas de réparation, couvrant une grande diversité de pièces et de dommages. L\'objectif : rendre ses clients (compagnies aériennes) plus autonomes dans le diagnostic et la réparation de leurs pièces, en leur donnant un accès simplifié à ce référentiel. Un enjeu business critique, car un avion immobilisé en hangar représente un coût très élevé pour les compagnies. La promesse : réduire les délais de réparation et fluidifier le travail des techniciens sur le terrain.',
    demarche: [
      { titre: 'Cadrage', desc: 'Définition des objectifs du POC et alignement des parties prenantes.' },
      { titre: 'Recherche utilisateur', desc: 'Interviews terrain pour comprendre les processus métier, analyse du flow de réparation en hangar, observation de l\'environnement utilisateur (contraintes physiques, outils existants), identification des leviers d\'amélioration.' },
      { titre: 'Co-conception', desc: 'Ateliers pour assurer l\'interopérabilité avec les différents référentiels et processus de réparation existants.' },
      { titre: 'Ateliers IA', desc: '2 mois d\'immersion avec l\'équipe IA pour comprendre les mécaniques des référentiels et entraîner le modèle.' },
      { titre: 'Conception & prototypage', desc: 'Maquettage haute fidélité, prototypage interactif, tests utilisateurs et itérations conjointes design / IA. Bonnes pratiques IA appliquées : explicabilité, contrôle utilisateur, information factuelle sans biais ni fausse certitude.' },
    ],
    defis: [
      { titre: 'Complexité des référentiels métier multiples', desc: 'Plusieurs référentiels coexistaient avec des logiques propres, rendant difficile la conception d\'un parcours unifié.', solution: 'Organisation de 2 mois d\'ateliers dédiés avec l\'équipe IA pour cartographier les mécaniques et concevoir une expérience capable de s\'adapter à cette diversité.' },
      { titre: 'Intégration des bonnes pratiques IA dans une UX métier exigeante', desc: 'Risque que les techniciens en hangar rejettent les suggestions de l\'IA si elles paraissaient opaques ou erronées.', solution: 'Application de principes d\'IA responsable (explicabilité, possibilité d\'amender la réponse, pas de réponse présentée comme certaine) intégrés dès la conception des écrans.' },
    ],
    resultats: [
      'POC validé par le client, démontrant le potentiel financier du produit',
      'Investissement de 190 K€ débloqué par le constructeur pour poursuivre le projet et concevoir l\'ensemble des parcours',
      'Industrialisation de l\'outil planifiée à l\'issue du développement complet',
    ],
    images: [
      // Les mockups occupent la pleine largeur, les écrans de l'outil sont
      // présentés en planche de trois pour rester compacts.
      // Mockups en pleine largeur (sources haute définition), puis le parcours
      // complet de l'outil en planche de trois.
      { src: 'Sources/annexe-book/sna-mockup-1.jpg', w: 2200, h: 1650, span: 'full', type: 'desktop', alt: 'L\'outil de diagnostic sur tablette', altEn: 'The diagnostic tool on a tablet' },
      { src: 'Sources/annexe-book/sna-parcours.jpg', w: 893, h: 341, span: 'full', type: 'full', alt: 'Parcours cible : du diagnostic terrain à la tâche de réparation', altEn: 'Target journey: from on-site diagnosis to the repair task' },
      { src: 'Sources/annexe-book/sna-mockup-2.jpg', w: 2200, h: 1466, span: 'full', type: 'desktop', alt: 'L\'outil en situation, en hangar', altEn: 'The tool in use, in the hangar' },
      { src: 'Sources/annexe-book/sna-mockup-3.jpg', w: 2200, h: 1466, span: 'full', type: 'desktop', alt: 'Prise de vue du dommage par le technicien', altEn: 'The technician photographing the damage' },
      { src: 'Sources/projets/aeronautique/Acceuil.png', w: 1171, h: 782, span: 'third', type: 'desktop', alt: 'Accueil de l\'outil', altEn: 'Tool home screen' },
      { src: 'Sources/projets/aeronautique/Nouveau%20diagnostic.png', w: 1171, h: 782, span: 'third', type: 'desktop', alt: 'Nouveau diagnostic — import et prise de photos', altEn: 'New diagnosis — importing and taking photos' },
      { src: 'Sources/projets/aeronautique/Plaque%20signal%C3%A9tique.png', w: 1171, h: 782, span: 'third', type: 'desktop', alt: 'Lecture de la plaque signalétique de la pièce', altEn: 'Reading the part nameplate' },
      { src: 'Sources/annexe-book/sna-ecran-resume.jpg', w: 1171, h: 782, span: 'third', type: 'desktop', alt: 'Résumé des photographies et des données récupérées', altEn: 'Summary of the photographs and data captured' },
      { src: 'Sources/projets/aeronautique/Analyse%20de%20l\'IA.png', w: 1171, h: 782, span: 'third', type: 'desktop', alt: 'Analyse du dommage par l\'IA', altEn: 'AI analysis of the damage' },
      { src: 'Sources/annexe-book/sna-ecran-rapport.jpg', w: 1171, h: 782, span: 'third', type: 'desktop', alt: 'Récapitulatif du damage report avant envoi', altEn: 'Damage report summary before sending' },
      { src: 'Sources/projets/aeronautique/R%C3%A9sultat%20du%20diagnostic.png', w: 1171, h: 782, span: 'third', type: 'desktop', alt: 'Résultat du diagnostic et tâche de réparation associée', altEn: 'Diagnosis result and matching repair task' },
    ],
    en: {
      titreCourt: 'Aeronautics & AI',
      clientCourt: 'Aerospace manufacturer',
      sousTitreCourt: 'Helping airlines diagnose and repair their parts faster with AI',
      titre: 'AI-assisted damage detection tool — POC',
      highlight: 'detection',
      type: 'Proof of Concept (POC) — professional tool integrating AI and image recognition',
      role: 'Product Designer (UX Research, UI Design, collaboration with AI team)',
      dureeCourte: '6 months',
      statut: 'Confidential',
      contexte: 'A major aircraft manufacturer holds a rich repository of several thousand repair cases, covering a wide variety of parts and damages. The goal: to make its clients (airlines) more autonomous in diagnosing and repairing their parts, by giving them simplified access to this repository. A critical business issue, as a grounded aircraft represents a very high cost for airlines. The promise: reduce repair times and streamline the work of field technicians.',
      demarche: [
        { titre: 'Scoping', desc: 'Defining the POC objectives and aligning stakeholders.' },
        { titre: 'User research', desc: 'Field interviews to understand business processes, analysis of the repair flow in the hangar, observation of the user environment (physical constraints, existing tools), identification of improvement levers.' },
        { titre: 'Co-design', desc: 'Workshops to ensure interoperability with the various existing repositories and repair processes.' },
        { titre: 'AI workshops', desc: '2 months of immersion with the AI team to understand the mechanics of the repositories and train the model.' },
        { titre: 'Design & prototyping', desc: 'High-fidelity wireframing, interactive prototyping, user testing and joint design/AI iterations. Responsible AI principles applied: explainability, user control, factual information without bias or false certainty.' },
      ],
      defis: [
        { titre: 'Complexity of multiple business repositories', desc: 'Several repositories coexisted with their own logic, making it difficult to design a unified journey.', solution: 'Organised 2 months of dedicated workshops with the AI team to map the mechanics and design an experience capable of adapting to this diversity.' },
        { titre: 'Integrating AI best practices into a demanding business UX', desc: 'Risk that hangar technicians would reject AI suggestions if they appeared opaque or incorrect.', solution: 'Application of responsible AI principles (explainability, ability to amend responses, no response presented as certain) integrated from the design phase.' },
      ],
      resultats: [
        'POC validated by the client, demonstrating the financial potential of the product',
        '€190K investment unlocked by the manufacturer to continue the project and design the complete journeys',
        'Tool industrialisation planned upon completion of full development',
      ],
      kpis: [
        { titre: '€190K', desc: 'Investment unlocked to continue the project and design all journeys' },
        { titre: 'POC validated', desc: 'Demonstrating the product\'s financial potential to the client' },
        { titre: 'Phase 2', desc: 'Tool industrialisation planned upon completion of full development' },
      ],
      competences: ['UX Research', 'AI & Design', 'Co-design', 'High-fidelity Prototyping', 'Responsible Design', 'Multidisciplinary Collaboration'],
      objectifs: [
        'Reduce aircraft ground time',
        'Make diagnosis easier from the moment the customer spots the damage',
        'Improve the existing repair reference database',
      ],
    },
  },

  {
    id: 3,
    num: '03',
    thumb: 'Sources/preview simulateur.png',
    titreCourt: 'Simulateur financier',
    sousTitreCourt: 'Conception du MVP d\'un simulateur financier pour des projets de recherche, après une réponse d\'appel d\'offre',
    clientCourt: 'Structure de valorisation de la recherche',
    highlight: 'simulation',
    dureeCourte: '6 mois',
    kpis: [
      { titre: 'MVP', desc: 'Livraison prévue le 30 mai 2026' },
      { titre: 'Accéléré', desc: 'Méthodologie de conception grâce au design system Telerik et au générateur d\'interface' },
      { titre: 'Validé', desc: 'Validation continue du client à chaque étape (cadrage, design, sprints)' },
    ],
    titre: 'Plateforme de simulation financière pour projets de recherche',
    sousTitre: 'Conception du MVP suite au gain de l\'appel d\'offre',
    client: 'SATT (Société d\'Accélération du Transfert de Technologies)',
    annee: '2025 — 2026',
    type: 'Conception et développement d\'un MVP — plateforme web métier multi-utilisateurs',
    role: 'Product Designer (UX Research, UI Design, collaboration tech & PO)',
    duree: '6 mois (réponse à l\'AO juillet 2025 · gain septembre 2025 · sprints du 1er décembre 2025 au 30 mai 2026)',
    equipe: '1 Lead UX-UI · 1 UX · 1 UI · 1 PO · 1 Dev Front · 1 Dev Back',
    outils: ['Figma', 'Mural'],
    statut: 'Confidentiel',
    competences: ['UX Research', 'Design System', 'Conception métier', 'Accompagnement PO', 'Collaboration Agile', 'Adaptation multi-profils utilisateurs'],
    contexte: 'La SATT porte une plateforme destinée à faciliter la conduite de projets de recherche partagés entre entreprises et universités. L\'enjeu : adresser des profils utilisateurs très hétérogènes — scientifiques et chercheurs expérimentés, services de financement en charge des décisions, mais aussi utilisateurs moins familiers du sujet. La plateforme doit donc proposer un outil expert pour les profils aguerris et rester accessible à des utilisateurs novices en matière de financement public ou privé.',
    demarche: [
      { titre: 'Cadrage', desc: 'Réalisé pendant la phase d\'appel d\'offre via plusieurs échanges avec le client, permettant d\'affiner sa vision et d\'identifier les enjeux clés du MVP.' },
      { titre: 'Recherche utilisateur', desc: '1 interview par typologie d\'utilisateur, ayant permis de corriger plusieurs flows définis dans le CDC qui ne reflétaient pas la réalité terrain.' },
      { titre: 'Parcours utilisateurs', desc: 'Formalisation des différents parcours à partir des enseignements des interviews.' },
      { titre: 'Conception', desc: 'Interface de formulaire pas-à-pas (proposée et validée dès l\'appel d\'offre), conçue à partir du design system Telerik pour exploiter un générateur d\'interface — choix qui a permis d\'accélérer significativement la phase de conception, de design et de développement.' },
      { titre: 'Phase dev', desc: 'Validation des écrans à chaque sprint, itérations selon les contraintes techniques, échanges continus avec l\'équipe de développement.' },
    ],
    defis: [
      { titre: 'Un Product Owner côté client sans expérience préalable dans ce rôle', desc: 'Le PO client manquait de temps et de culture agile pour structurer un backlog exploitable.', solution: 'Mise en place d\'un PO interne en accompagnement, et animation d\'ateliers dédiés (Product Vision, Roadmap, priorisation des sprints) pour structurer le pilotage produit.' },
      { titre: 'Un métier technique complexe (calculs financiers spécifiques)', desc: 'La phase d\'acculturation a pris du temps pour l\'ensemble de l\'équipe.', solution: 'Mutualisation des connaissances acquises tout au long du projet et restitution structurée aux développeurs pour leur donner une vision métier claire et partagée.' },
    ],
    resultats: [
      'MVP en cours — livraison prévue le 30/05/2026',
      'Méthodologie de conception accélérée grâce au choix du design system Telerik et du générateur d\'interface',
      'Validation continue du client à chaque étape (cadrage, design, sprints)',
    ],
    images: [
      { src: 'Sources/projets/simulateur%20financier/annexlabe%20simulation%201%201.png', w: 646, h: 420, type: 'desktop', alt: 'Liste des simulations', altEn: 'Simulation list' },
      { src: 'Sources/projets/simulateur%20financier/annexlabe%20simulation%202%201.png', w: 647, h: 420, type: 'desktop', alt: 'Formulaire de simulation', altEn: 'Simulation form' },
    ],
    en: {
      titreCourt: 'Financial simulator',
      clientCourt: 'Research commercialisation body',
      sousTitreCourt: 'Designing the MVP of a financial simulator for research projects, following an RFP response',
      titre: 'Financial simulation platform for research projects',
      highlight: 'simulation',
      type: 'MVP design and development — multi-user professional web platform',
      role: 'Product Designer (UX Research, UI Design, tech & PO collaboration)',
      dureeCourte: '6 months',
      statut: 'Confidential',
      contexte: 'The SATT supports a platform designed to facilitate the management of shared research projects between companies and universities. The challenge: addressing very diverse user profiles — experienced scientists and researchers, finance teams in charge of decisions, and users less familiar with the subject. The platform must therefore offer an expert tool for experienced profiles while remaining accessible to users unfamiliar with public or private funding.',
      demarche: [
        { titre: 'Scoping', desc: 'Conducted during the RFP phase through several exchanges with the client, refining their vision and identifying key MVP challenges.' },
        { titre: 'User research', desc: '1 interview per user type, which corrected several flows defined in the specifications that did not reflect field reality.' },
        { titre: 'User journeys', desc: 'Formalising the different journeys based on insights from interviews.' },
        { titre: 'Design', desc: 'Step-by-step form interface (proposed and validated during the RFP), designed using the Telerik design system to leverage an interface generator — a choice that significantly accelerated the design and development phases.' },
        { titre: 'Dev phase', desc: 'Screen validation at each sprint, iterations based on technical constraints, ongoing exchanges with the development team.' },
      ],
      defis: [
        { titre: 'A client-side Product Owner with no prior experience in the role', desc: 'The client PO lacked time and agile culture to structure a workable backlog.', solution: 'Set up an internal supporting PO, and facilitated dedicated workshops (Product Vision, Roadmap, sprint prioritisation) to structure product management.' },
        { titre: 'A complex technical domain (specific financial calculations)', desc: 'The onboarding phase took time for the entire team.', solution: 'Pooled knowledge acquired throughout the project and structured restitution to developers to give them a clear, shared business understanding.' },
      ],
      resultats: [
        'MVP in progress — delivery scheduled for 30/05/2026',
        'Accelerated design methodology thanks to the Telerik design system and interface generator',
        'Continuous client validation at each stage (scoping, design, sprints)',
      ],
      kpis: [
        { titre: 'MVP', desc: 'Delivery scheduled for 30 May 2026' },
        { titre: 'Accelerated', desc: 'Design methodology accelerated thanks to the Telerik design system and interface generator' },
        { titre: 'Validated', desc: 'Continuous client validation at each stage (scoping, design, sprints)' },
      ],
      competences: ['UX Research', 'Design System', 'Business Design', 'PO Support', 'Agile Collaboration', 'Multi-profile User Adaptation'],
    },
  },

  {
    id: 4,
    num: '04',
    thumb: 'Sources/preview design system.png',
    titreCourt: 'Design System',
    sousTitreCourt: 'Création from scratch du design system d\'une entreprise multi-marque',
    clientCourt: 'Entreprise multi-marque',
    highlight: 'Design System',
    dureeCourte: '1 an et 6 mois',
    kpis: [
      { titre: '38', desc: 'Composants livrés avec leurs variants et leur double documentation' },
      { titre: 'Adopté', desc: 'Forte adoption par les équipes design et développement' },
      { titre: 'Unifié', desc: 'Cohérence visuelle assurée entre les différentes marques et outils de l\'écosystème' },
    ],
    titre: 'Conception d\'un Design System multi-marque',
    sousTitre: 'Création from scratch du design system d\'une entreprise multi-marque',
    client: 'Entreprise multi-marque',
    annee: '2024 — 2025',
    type: 'Création d\'un Design System scalable — composants React et Angular, documentation design & dev',
    role: 'Designer (analyse technique, recherche d\'usage, conception des composants)',
    duree: '1 an et 6 mois',
    equipe: '1 Lead UX-UI · 1 Designer · 1 Tech Lead · 1 Développeur',
    outils: ['Figma', 'Telerik', 'Mural', 'Zeplin', 'Azure'],
    statut: 'Confidentiel',
    competences: ['Design System', 'Conception de composants', 'Documentation design & dev', 'Collaboration tech', 'Material Design', 'Multi-framework (React / Angular)', 'Figma branching'],
    methodo: [
      { titre: 'Méthodologie', items: [
        'Atomic design',
        'Design tokens co-construits avec les développeurs',
        'Méthodologie en sprint : design sprints menés en parallèle des sprints de développement',
        'Pour chaque composant réalisé, veille sur les design systems de l\'État, de Michelin et surtout Material 3',
        'Deux designers sur le projet, travail en branche avant de merger une fois le composant complet et documenté',
      ] },
    ],
    contexte: 'Une entreprise multi-marque souhaitait se doter d\'un Design System unifié, capable de s\'adapter sans friction à l\'identité de chacune de ses marques. L\'objectif : accélérer les développements futurs, garantir la cohérence visuelle entre les différents outils et marques, et poser des fondations techniques solides pour l\'écosystème produit.',
    demarche: [
      { titre: 'Inspiration & cadrage', desc: 'Design system pensé dans l\'esprit du Material Design, adapté aux contraintes multi-marque.' },
      { titre: 'Organisation projet', desc: 'Design sprints parallélisés avec les sprints de développement, cérémonies communes entre les deux équipes pour assurer un alignement continu.' },
      { titre: 'Répartition design', desc: 'Tâches de conception réparties entre les deux designers, avec utilisation du système de branches Figma pour itérer sans casser les composants déjà validés.' },
      { titre: 'Conception', desc: 'Analyse technique conjointe avec l\'équipe dev pour garantir l\'adaptabilité des composants à différents langages (React, Angular), technologies et supports.' },
      { titre: 'Livrable final', desc: '38 composants intégrant l\'ensemble de leurs variants, accompagnés d\'une double documentation : l\'une pour les designers, l\'autre pour les développeurs.' },
    ],
    defis: [
      { titre: 'Complexité technique multi-environnement', desc: 'Conception de composants suffisamment flexibles pour fonctionner sur plusieurs frameworks (React, Angular), supports et identités de marque, sans dégradation de cohérence.', solution: 'Travail rapproché et continu avec l\'équipe technique dès la phase de conception, intégration des contraintes dev en amont du design, et validation systématique de la faisabilité de chaque composant avant industrialisation.' },
    ],
    resultats: [
      '38 composants livrés avec leurs variants et leur double documentation',
      'Temps de développement réduit sur les nouveaux projets grâce à la réutilisation des composants',
      'Forte adoption par les équipes design et développement',
      'Cohérence visuelle assurée entre les différentes marques et outils de l\'écosystème',
    ],
    images: [
      { src: 'Sources/projets/Design%20System/image%202.png', w: 1322, h: 209, span: 'full', type: 'full',    alt: 'Documentation couleurs & typographie', altEn: 'Colour & typography documentation' },
      { src: 'Sources/projets/Design%20System/image%201.png', w: 522, h: 532, type: 'desktop', alt: 'Vue composants — Figma', altEn: 'Component view — Figma' },
      { src: 'Sources/projets/Design%20System/image%203.png', w: 768, h: 532, type: 'desktop', alt: 'Panel variables — tokens de couleur', altEn: 'Variables panel — colour tokens' },
      { src: 'Sources/annexe-book/covage-1.jpg', w: 402, h: 753, span: 'narrow', type: 'desktop', alt: 'Documentation d\'un composant — anatomie et usages', altEn: 'Component documentation — anatomy and usage' },
      { src: 'Sources/annexe-book/covage-2.jpg', w: 415, h: 1080, span: 'narrow', type: 'desktop', alt: 'Guidelines : tailles, états et cas d\'usage', altEn: 'Guidelines: sizes, states and use cases' },
    ],
    en: {
      titreCourt: 'Design System',
      clientCourt: 'Multi-brand company',
      sousTitreCourt: 'Creating a multi-brand Design System from scratch',
      titre: 'Multi-brand Design System design',
      highlight: 'Design System',
      type: 'Scalable Design System — React and Angular components, design & dev documentation',
      role: 'Designer (technical analysis, usage research, component design)',
      dureeCourte: '1 year and 6 months',
      statut: 'Confidential',
      contexte: 'A multi-brand company wanted to equip itself with a unified Design System, capable of adapting seamlessly to each brand\'s identity. The objective: accelerate future developments, ensure visual consistency across the various tools and brands, and lay solid technical foundations for the product ecosystem.',
      demarche: [
        { titre: 'Inspiration & scoping', desc: 'Design system conceived in the spirit of Material Design, adapted to multi-brand constraints.' },
        { titre: 'Project organisation', desc: 'Design sprints parallelised with development sprints, joint ceremonies between both teams to ensure ongoing alignment.' },
        { titre: 'Design distribution', desc: 'Tasks distributed between the two designers, using the Figma branching system to iterate without breaking already-validated components.' },
        { titre: 'Design', desc: 'Joint technical analysis with the dev team to ensure component adaptability across different languages (React, Angular), technologies and platforms.' },
        { titre: 'Final deliverable', desc: '38 components including all their variants, accompanied by dual documentation: one for designers, the other for developers.' },
      ],
      defis: [
        { titre: 'Multi-environment technical complexity', desc: 'Designing components flexible enough to work across multiple frameworks (React, Angular), platforms and brand identities, without degrading consistency.', solution: 'Close and ongoing collaboration with the technical team from the design phase, integrating dev constraints upstream, and systematic feasibility validation of each component before industrialisation.' },
      ],
      resultats: [
        '38 components delivered with their variants and dual documentation',
        'Reduced development time on new projects thanks to component reuse',
        'Strong adoption by design and development teams',
        'Visual consistency ensured across the various brands and tools in the ecosystem',
      ],
      kpis: [
        { titre: '38', desc: 'Components delivered with their variants and dual documentation' },
        { titre: 'Adopted', desc: 'Strong adoption by design and development teams' },
        { titre: 'Unified', desc: 'Visual consistency ensured across different brands and ecosystem tools' },
      ],
      competences: ['Design System', 'Component Design', 'Design & Dev Documentation', 'Tech Collaboration', 'Material Design', 'Multi-framework (React / Angular)', 'Figma Branching'],
      methodo: [
        { titre: 'Methodology', items: [
          'Atomic design',
          'Design tokens co-built with the developers',
          'Sprint-based methodology: design sprints run in parallel with development sprints',
          'For every component, benchmarking against public-sector, Michelin and above all Material 3 design systems',
          'Two designers on the project, working on branches and merging once a component is complete and documented',
        ] },
      ],
    },
  },

  {
    id: 5,
    num: '05',
    thumb: 'Sources/annexe-book/edc-hero.jpg',
    titreCourt: 'Migration & refonte',
    sousTitreCourt: 'Refonte ergonomique d\'un logiciel métier de gestion des cautionnements',
    clientCourt: 'Acteur du cautionnement financier',
    highlight: 'refonte',
    dureeCourte: '',
    titre: 'Migration et refonte d\'un logiciel métier de cautionnement',
    sousTitre: 'Refonte ergonomique d\'un logiciel métier de gestion des cautionnements',
    client: 'Entreprise du secteur du cautionnement financier',
    annee: '',
    type: 'Logiciel métier interne — migration fonctionnelle et refonte de parcours',
    role: 'Product Designer (UX Research, UI Design, prémaquettes HTML)',
    duree: '',
    equipe: '',
    outils: ['Figma', 'Claude Code', 'HTML'],
    statut: 'Confidentiel',
    competences: ['UX Research', 'Atelier de cadrage', 'Tri par cartes', 'Prémaquettes HTML', 'Design System', 'Figma Dev Mode'],
    contexte: 'L\'entreprise, spécialisée dans le cautionnement, intègre de nouvelles fonctionnalités dans le logiciel interne utilisé par ses équipes opérationnelles. L\'outil existant contient déjà une partie des briques fonctionnelles à migrer, mais certains parcours — prêts amortissables, transferts de société — n\'existent pas et doivent être créés de zéro. Conçu à l\'origine sans étude utilisateur préalable, il pose de vraies difficultés aux métiers : la migration est l\'occasion de refondre l\'ergonomie des parcours ciblés.',
    demarche: [
      { titre: 'Atelier de cadrage', desc: 'Définition des parcours types actuels pour les deux métiers impactés, puis recueil des besoins à chaque étape : ce qui doit être amélioré, ce qui manque, et ce qui ne doit surtout pas disparaître.' },
      { titre: 'Co-construction avec la DSI', desc: 'Une fois les parcours posés par les métiers, les points bloquants, à éclaircir ou non réalisables sont repris par la technique.' },
      { titre: 'Tri par cartes', desc: 'Atelier de tri par cartes des données page par page, mené avec le métier.' },
      { titre: 'Prémaquettes HTML', desc: 'Conception de maquettes HTML avec Claude Code pour valider vite les structures de page avant de passer à Figma.' },
      { titre: 'Maquettes & handoff', desc: 'Une fois les prémaquettes stabilisées, production des maquettes dans Figma avec le design system et les variables, partagées aux développeurs via Figma Dev Mode.' },
    ],
    defis: [
      { titre: 'Des profils qui imposent leur vision en atelier', desc: 'Nous savions que certains participants, plus bavards, auraient tendance à imposer leur vision du produit au reste du groupe.', solution: 'Mise en place d\'un bâton de parole — une poule en peluche — qui a également servi de balle anti-stress lors des échanges les plus tendus.' },
    ],
    resultats: [],
    images: [
      // Le mockup ouvre la galerie sur toute la largeur, les photos d'atelier suivent.
      { src: 'Sources/annexe-book/edc-hero.jpg', w: 1800, h: 1350, span: 'full', type: 'desktop', alt: 'Écran de saisie d\'un prêt', altEn: 'Loan entry screen' },
      { src: 'Sources/annexe-book/edc-atelier-1.jpg', w: 1134, h: 2016, span: 'narrow', type: 'mobile', alt: 'Atelier de cadrage — co-construction des parcours au mur', altEn: 'Scoping workshop — co-building the journeys on the wall' },
      { src: 'Sources/annexe-book/edc-atelier-2.jpg', w: 1134, h: 2016, span: 'narrow', type: 'mobile', alt: 'Types, informations, états et événements posés en atelier', altEn: 'Types, data, statuses and events mapped in the workshop' },
      { src: 'Sources/annexe-book/edc-atelier-3.jpg', w: 1134, h: 2016, span: 'narrow', type: 'mobile', alt: 'Le « bâton de parole » de l\'atelier', altEn: 'The workshop \u201Ctalking stick\u201D' },
      { src: 'Sources/annexe-book/edc-atelier-4.jpg', w: 1134, h: 2016, span: 'narrow', type: 'mobile', alt: 'Table de travail pendant l\'atelier de cadrage', altEn: 'The working table during the scoping workshop' },
    ],
    en: {
      titreCourt: 'Migration & redesign',
      sousTitreCourt: 'Ergonomic redesign of a guarantee-management business tool',
      titre: 'Migration and redesign of a guarantee-management business tool',
      clientCourt: 'Financial guarantee provider',
      highlight: 'redesign',
      type: 'Internal business software — functional migration and journey redesign',
      role: 'Product Designer (UX Research, UI Design, HTML pre-mockups)',
      dureeCourte: '',
      statut: 'Confidential',
      contexte: 'The company, specialised in financial guarantees, is adding new features to the internal software used by its operational teams. The existing tool already contains some of the functional building blocks to migrate, but certain journeys — amortisable loans, company transfers — do not exist and have to be built from scratch. Originally designed without any prior user research, it causes real difficulties for business teams: the migration is the opportunity to redesign the ergonomics of the targeted journeys.',
      demarche: [
        { titre: 'Scoping workshop', desc: 'Mapping the current journeys for the two business teams involved, then gathering needs at each step: what should be improved, what is missing, and what must absolutely not disappear.' },
        { titre: 'Co-construction with IT', desc: 'Once journeys were mapped by the business teams, blockers, open questions and unfeasible items were raised by the technical side.' },
        { titre: 'Card sorting', desc: 'Card sorting workshop on page-by-page data, run with the business teams.' },
        { titre: 'HTML pre-mockups', desc: 'HTML mockups built with Claude Code to validate page structures quickly before moving to Figma.' },
        { titre: 'Design & handoff', desc: 'Once pre-mockups were stable, final designs produced in Figma with the design system and variables, shared with developers via Figma Dev Mode.' },
      ],
      defis: [
        { titre: 'Participants imposing their own product vision', desc: 'We knew some of the more talkative participants would tend to impose their vision on the rest of the group.', solution: 'We introduced a talking stick — a plush hen — which also doubled as a stress ball during the tenser discussions.' },
      ],
      resultats: [],
      competences: ['UX Research', 'Scoping workshop', 'Card sorting', 'HTML pre-mockups', 'Design System', 'Figma Dev Mode'],
    },
  },

  {
    id: 6,
    num: '06',
    thumb: 'Sources/annexe-book/afm-multiscreen.jpg',
    banner: 'Sources/annexe-book/afm-multiscreen.jpg',
    titreCourt: 'Portail familles & LLM',
    sousTitreCourt: 'Accompagner les familles dans le parcours d\'acquisition d\'un fauteuil roulant',
    clientCourt: 'Association nationale de santé',
    highlight: 'accessible',
    dureeCourte: '',
    titre: 'Portail d\'accompagnement des familles assisté par un agent LLM',
    sousTitre: 'Accompagner les familles dans le parcours d\'acquisition d\'un fauteuil roulant',
    client: 'Association nationale d\'accompagnement des familles (santé)',
    annee: '',
    type: 'Applications iOS, Android et back-office',
    role: 'Product Designer (UX Research, UI Design, accompagnement PO)',
    duree: '',
    equipe: '',
    outils: ['Figma', 'Mural'],
    statut: 'Confidentiel',
    competences: ['UX Research', 'Accessibilité RGAA', 'Atelier de zoning', 'Conception avec LLM', 'Guide de style', 'Illustration', 'Accompagnement PO'],
    contexte: 'L\'association souhaite réaliser un portail à destination des familles qu\'elle accompagne, ou qu\'elle est en capacité d\'accompagner. La nouvelle réforme du remboursement des fauteuils roulants offre le contexte idéal pour en poser la première brique : le parcours d\'acquisition d\'un fauteuil. Pour accompagner les familles à travers des besoins très hétérogènes, le choix d\'un agent LLM s\'est révélé le plus pertinent.',
    demarche: [
      { titre: 'Recherche & étude', desc: 'Atelier métiers et interviews utilisateurs pour comprendre les situations réelles des familles accompagnées.' },
      { titre: 'Atelier de zoning', desc: 'L\'application s\'adressant à des personnes en situation de handicap — ou à leurs proches — à différents niveaux, nous avons mené un atelier de zoning pour construire une application adaptée au RGAA : visuellement, en termes de structure, mais aussi pour que le LLM soit accessible à tous.' },
      { titre: 'Repérage des bonnes pratiques', desc: 'Démonstration visuelle de ce qui se fait aujourd\'hui sur mobile, avec les exemples d\'outils natifs iOS et Android — la bonne élève de l\'exercice fut l\'Identité Numérique. Puis affinage des fonctionnalités : « comment naviguer dans l\'application ? », « commandes vocales, natives ou à implémenter ? ».' },
      { titre: 'Conception', desc: 'Proposition d\'un guide de style sur la base de la charte existante, mais adouci. Propositions et réalisation d\'illustrations. Maquettes prototypées, conçues responsive, accessibles et « mains libres ».' },
      { titre: 'Accompagnement PO', desc: 'Contribution au backlog et participation aux cérémonies agiles.' },
    ],
    defis: [],
    resultats: [],
    enjeux: 'L\'enjeu majeur portait sur la perception de l\'application par des utilisateurs se trouvant dans des situations complexes : le ton, les couleurs et le rythme du parcours ne pouvaient pas être ceux d\'un produit standard. S\'y ajoutait l\'intégration d\'un LLM fourni par un prestataire, à faire tenir dans un parcours entièrement conforme au RGAA.',
    images: [
      // afm-multiscreen.jpg sert de vignette et de bandeau (champs `thumb` et
      // `banner`) : volontairement absente de la galerie pour ne pas la répéter.
      { src: 'Sources/annexe/afm-hero.jpg', w: 1800, h: 1350, type: 'mobile', alt: 'Écrans de l\'application mobile', altEn: 'Mobile app screens' },
      { src: 'Sources/annexe/afm-1.jpg', w: 1800, h: 1350, type: 'mobile', alt: 'Parcours d\'accompagnement', altEn: 'Support journey' },
      { src: 'Sources/annexe/afm-2.jpg', w: 1800, h: 1350, type: 'mobile', alt: 'Agent conversationnel', altEn: 'Conversational agent' },
      { src: 'Sources/annexe/afm-3.jpg', w: 1800, h: 1350, type: 'mobile', alt: 'Écrans de contenu', altEn: 'Content screens' },
    ],
    en: {
      titreCourt: 'Family portal & LLM',
      sousTitreCourt: 'Supporting families through the journey of acquiring a wheelchair',
      titre: 'Family support portal assisted by an LLM agent',
      clientCourt: 'National health association',
      highlight: 'accessible',
      type: 'iOS, Android and back-office applications',
      role: 'Product Designer (UX Research, UI Design, PO support)',
      dureeCourte: '',
      statut: 'Confidential',
      contexte: 'The association wanted to build a portal for the families it supports, or is able to support. The new wheelchair reimbursement reform offered the ideal context for laying its first building block: the wheelchair acquisition journey. To support families across highly varied needs, an LLM agent proved the most relevant choice.',
      demarche: [
        { titre: 'Research & study', desc: 'Business workshop and user interviews to understand the real situations of the families supported.' },
        { titre: 'Zoning workshop', desc: 'As the app addresses people with disabilities — or their relatives — at varying levels, we ran a zoning workshop to build an app compliant with the French RGAA accessibility standard: visually, structurally, and so that the LLM itself would be accessible to everyone.' },
        { titre: 'Best-practice review', desc: 'Visual review of current mobile practice, with native iOS and Android examples — the star of the exercise was the French digital identity app. Then feature refinement: "how do you navigate the app?", "voice commands, native or to implement?".' },
        { titre: 'Design', desc: 'Style guide proposed on the basis of the existing brand guidelines, but softened. Illustration proposals and production. Prototyped designs, built responsive, accessible and hands-free.' },
        { titre: 'PO support', desc: 'Backlog contribution and participation in agile ceremonies.' },
      ],
      defis: [],
      resultats: [],
      enjeux: 'The main challenge concerned how the app would be perceived by users in complex personal situations: tone, colours and journey pacing could not be those of a standard product. On top of that, an LLM supplied by an external provider had to fit inside a journey fully compliant with the RGAA accessibility standard.',
      competences: ['UX Research', 'RGAA accessibility', 'Zoning workshop', 'Designing with LLMs', 'Style guide', 'Illustration', 'PO support'],
    },
  },

  {
    id: 7,
    num: '07',
    thumb: 'Sources/annexe-book/per-inter-hero.jpg',
    titreCourt: 'Refonte CRM',
    sousTitreCourt: 'Concevoir un CRM sur-mesure pour remplacer un outil de gestion coûteux et surdimensionné',
    clientCourt: 'Grossiste en produits alimentaires',
    highlight: 'sur-mesure',
    dureeCourte: '',
    titre: 'Refonte d\'un CRM métier pour un grossiste alimentaire',
    sousTitre: 'Concevoir un CRM sur-mesure pour remplacer un outil de gestion coûteux et surdimensionné',
    client: 'Grossiste en fromages et spécialités européennes (B2B)',
    annee: '',
    type: 'CRM métier — stocks, fournisseurs et clients',
    role: 'Product Designer (cadrage, UX Research, UI Design)',
    duree: '',
    equipe: '',
    outils: ['Figma', 'Mural'],
    statut: 'Confidentiel',
    competences: ['Atelier de cadrage', 'Service Blueprint', 'Atelier persona', 'Priorisation', 'UI Design', 'Conception de CRM'],
    contexte: 'Depuis 35 ans, ce grossiste propose un large assortiment de fromages et de spécialités d\'Europe aux professionnels de l\'alimentation et de la distribution — restauration, grande distribution, industrie agroalimentaire. L\'entreprise s\'appuyait sur un outil de gestion unique pour ses stocks, ses fournisseurs et ses clients : un logiciel onéreux, riche de fonctionnalités jamais utilisées et de parcours complexes. D\'où la volonté de concevoir son propre CRM, adapté à son métier et à ses usages.',
    methodo: [
      { titre: 'Cadrage', items: ['Atelier de cadrage des objectifs et fonctionnalités clés', 'Atelier d\'exploration autour des usages métiers', 'Service Blueprint', 'Priorisation des fonctionnalités', 'Priorisation des pages à concevoir'] },
      { titre: 'Design', items: ['Propositions de visuels en adéquation avec la charte', 'Réalisation des écrans dits « répétitifs » pour générer les pages rapidement', 'Conception des pages plus complexes, adaptées aux besoins métiers'] },
    ],
    demarche: [],
    defis: [],
    resultats: [],
    images: [
      { src: 'Sources/annexe-book/per-inter-hero.jpg', w: 943, h: 1082, type: 'desktop', alt: 'Écrans du CRM', altEn: 'CRM screens' },
      { src: 'Sources/annexe-book/per-inter-1.jpg', w: 685, h: 317, span: 'full', type: 'desktop', alt: 'Service Blueprint', altEn: 'Service Blueprint' },
      { src: 'Sources/annexe-book/per-inter-2.jpg', w: 684, h: 243, span: 'full', type: 'desktop', alt: 'Atelier persona', altEn: 'Persona workshop' },
    ],
    en: {
      titreCourt: 'CRM redesign',
      sousTitreCourt: 'Designing a bespoke CRM to replace an expensive, oversized management tool',
      titre: 'Redesign of a business CRM for a food wholesaler',
      clientCourt: 'Food wholesaler',
      highlight: 'bespoke',
      type: 'Business CRM — stock, suppliers and customers',
      role: 'Product Designer (scoping, UX Research, UI Design)',
      dureeCourte: '',
      statut: 'Confidential',
      contexte: 'For 35 years, this wholesaler has offered a wide assortment of European cheeses and specialities to food and retail professionals — catering, mass retail and the food industry. The company relied on a single management tool for its stock, suppliers and customers: expensive software, full of features never used and complex journeys. Hence the decision to build its own CRM, tailored to its business and its everyday use.',
      methodo: [
        { titre: 'Scoping', items: ['Workshop framing objectives and key features', 'Exploration workshop around business practices', 'Service Blueprint', 'Feature prioritisation', 'Prioritisation of the pages to design'] },
        { titre: 'Design', items: ['Visual proposals aligned with the brand guidelines', 'Production of the "repetitive" screens to generate pages quickly', 'Design of the more complex pages, adapted to business needs'] },
      ],
      demarche: [],
      defis: [],
      resultats: [],
      competences: ['Scoping workshop', 'Service Blueprint', 'Persona workshop', 'Prioritisation', 'UI Design', 'CRM design'],
    },
  },

  {
    id: 8,
    num: '08',
    thumb: 'Sources/annexe/sdmis-hero.jpg',
    titreCourt: 'Application no-desk',
    sousTitreCourt: 'Diffuser l\'information à plus de 5 000 sapeurs-pompiers volontaires sans poste de travail',
    clientCourt: 'Service départemental d\'incendie et de secours',
    highlight: 'no-desk',
    dureeCourte: '',
    titre: 'Application mobile no-desk pour un service d\'incendie et de secours',
    sousTitre: 'Diffuser l\'information à plus de 5 000 sapeurs-pompiers volontaires sans poste de travail',
    client: 'Service départemental-métropolitain d\'incendie et de secours',
    annee: '',
    type: 'Application mobile de diffusion d\'information interne',
    role: 'Product Designer (cadrage, UX Research, UI Design)',
    duree: '',
    equipe: '',
    outils: ['Figma', 'Mural'],
    statut: 'Confidentiel',
    competences: ['Cadrage', 'Entretiens utilisateurs & experts', 'Immersion terrain', 'Atelier de parcours & arborescence', 'Co-conception', 'Wireframes', 'Tests utilisateurs'],
    contexte: 'Ce service départemental-métropolitain d\'incendie et de secours, c\'est près de 100 casernes et 110 000 opérations par an, sur lesquelles interviennent à la fois des pompiers professionnels et plus de 5 000 pompiers volontaires. Ces sapeurs-pompiers n\'ont pas tous accès facilement à l\'information via un ordinateur de bureau : aujourd\'hui, la diffusion peut encore se faire, par exemple, via l\'envoi d\'un PDF. L\'objectif est d\'atteindre ces pompiers par un vecteur no-desk sur mobile, pour leur pousser de l\'information, les tenir au courant des actualités et leur diffuser des contenus.',
    methodo: [
      { titre: '01 — Comprendre', items: ['Analyse de l\'existant : toutes les sources d\'information disponibles, les outils comme les communications dans les casernes', 'Étude utilisateurs : rencontre avec les pompiers professionnels et volontaires', 'Visite des casernes et découverte des supports de communication'] },
      { titre: '02 — Co-concevoir', items: ['Atelier d\'idéation et de priorisation', 'Définition des parcours et zoning des écrans', 'Atelier technico-fonctionnel avec le PO et le Scrum Master'] },
      { titre: '03 — Transformer', items: ['Wireframes', 'Tests d\'utilisabilité', 'Maquettes prototypées'] },
    ],
    demarche: [],
    defis: [],
    resultats: [],
    images: [
      { src: 'Sources/annexe/sdmis-hero.jpg', w: 1800, h: 1200, type: 'mobile', alt: 'Écrans de l\'application', altEn: 'App screens' },
      { src: 'Sources/annexe/sdmis-1.jpg', w: 1800, h: 1200, type: 'mobile', alt: 'Fil d\'actualités', altEn: 'News feed' },
    ],
    en: {
      titreCourt: 'No-desk app',
      sousTitreCourt: 'Reaching over 5,000 volunteer firefighters with no workstation',
      titre: 'No-desk mobile app for a fire and rescue service',
      clientCourt: 'Departmental fire and rescue service',
      highlight: 'no-desk',
      type: 'Mobile app for internal information distribution',
      role: 'Product Designer (scoping, UX Research, UI Design)',
      dureeCourte: '',
      statut: 'Confidential',
      contexte: 'This departmental and metropolitan fire and rescue service runs nearly 100 stations and 110,000 operations a year, staffed by both professional firefighters and more than 5,000 volunteers. Not all of them have easy access to information from a desktop computer: today, distribution can still happen by sending out a PDF. The objective is to reach these firefighters through a no-desk mobile channel, to push information to them, keep them up to date and distribute content.',
      methodo: [
        { titre: '01 — Understand', items: ['Analysis of what exists: every available information source, from tools to the communications posted in stations', 'User research: meeting professional and volunteer firefighters', 'Station visits and review of communication materials'] },
        { titre: '02 — Co-design', items: ['Ideation and prioritisation workshop', 'Journey definition and screen zoning', 'Technical-functional workshop with the PO and Scrum Master'] },
        { titre: '03 — Transform', items: ['Wireframes', 'Usability testing', 'Prototyped designs'] },
      ],
      demarche: [],
      defis: [],
      resultats: [],
      competences: ['Scoping', 'User & expert interviews', 'Field immersion', 'Journey & tree-structure workshops', 'Co-design', 'Wireframes', 'User testing'],
    },
  },

  {
    id: 9,
    num: '09',
    thumb: 'Sources/annexe-book/eurexo-ipad-1.jpg',
    banner: 'Sources/annexe-book/eurexo-mobile.jpg',
    titreCourt: 'Espace assurés',
    sousTitreCourt: 'Donner aux assurés l\'autonomie sur le suivi de leur dossier de sinistre',
    clientCourt: 'Acteur de l\'expertise sinistre en assurance',
    highlight: 'autonomie',
    dureeCourte: '',
    titre: 'Refonte de l\'espace assurés d\'un acteur de l\'expertise sinistre',
    sousTitre: 'Donner aux assurés l\'autonomie sur le suivi de leur dossier de sinistre',
    client: 'Acteur de l\'expertise sinistre, entre assureurs et assurés',
    annee: '',
    type: 'Application web responsive — espace client multi-device',
    role: 'Product Designer (audit ergonomique, UX Research, UI Design)',
    duree: '',
    equipe: '',
    outils: ['Figma', 'Mural'],
    statut: 'Confidentiel',
    competences: ['Audit ergonomique', 'Ateliers métiers', 'Entretiens utilisateurs', 'Mobile-first', 'Responsive multi-device', 'Tests utilisateurs', 'Propositions graphiques'],
    contexte: 'Ce cabinet, lien entre les assureurs et les assurés lors d\'un sinistre, souhaite refondre son « espace assurés » permettant à ces derniers de suivre leurs dossiers en cours. L\'objectif de cette application est de donner davantage d\'autonomie à l\'assuré dans le suivi de son dossier et dans les démarches nécessaires à son bon déroulement. Le parcours de prise de rendez-vous est l\'un des enjeux majeurs de cette refonte.',
    demarche: [
      { titre: 'Audit ergonomique', desc: 'Analyse de l\'existant et identification des points de friction du parcours actuel.' },
      { titre: 'Ateliers métiers', desc: 'Ateliers avec les équipes métiers pour comprendre les différentes étapes de la qualification d\'un sinistre.' },
      { titre: 'Recherche utilisateur', desc: 'Entretiens avec les clients finaux — les sinistrés — pour comprendre leurs attentes et leurs objectifs.' },
      { titre: 'Conception mobile-first', desc: 'Réalisation ergonomique en mobile-first des maquettes, garantissant un outil responsive sur tous les devices.' },
      { titre: 'Tests & itérations', desc: 'Tests utilisateurs, itérations et propositions graphiques.' },
    ],
    defis: [],
    resultats: [],
    images: [
      // Les deux tablettes partagent le même format pour s'aligner en hauteur.
      { src: 'Sources/annexe-book/eurexo-ipad-1.jpg', w: 1800, h: 1721, ratio: '4 / 3', type: 'desktop', alt: 'L\'espace assurés sur tablette', altEn: 'The policyholder area on a tablet' },
      { src: 'Sources/annexe-book/eurexo-mobile.jpg', w: 1800, h: 1200, type: 'full', alt: 'Le parcours mobile-first : suivi de dossier, prise de rendez-vous et messagerie', altEn: 'The mobile-first journey: claim tracking, appointment booking and messaging' },
      { src: 'Sources/annexe-book/eurexo-ipad-2.jpg', w: 1800, h: 1350, ratio: '4 / 3', type: 'desktop', alt: 'Tableau de bord du dossier de sinistre', altEn: 'Claim dashboard' },
      // eurexo-1.jpg et eurexo-2.jpg retirés : doublons exacts de
      // eurexo-ipad-1 et eurexo-ipad-2, en moins bonne qualité.
      // Le mockup ordinateur ferme la galerie, sur toute la largeur.
      { src: 'Sources/annexe-book/eurexo-laptop.jpg', w: 1800, h: 1215, span: 'full', zoom: 1.2, type: 'desktop', alt: 'La même interface sur ordinateur', altEn: 'The same interface on desktop' },
    ],
    en: {
      titreCourt: 'Policyholder area',
      sousTitreCourt: 'Giving policyholders autonomy in tracking their claim',
      titre: 'Redesign of the policyholder area for a claims assessment firm',
      clientCourt: 'Insurance claims assessment firm',
      highlight: 'autonomy',
      type: 'Responsive web application — multi-device customer area',
      role: 'Product Designer (ergonomic audit, UX Research, UI Design)',
      dureeCourte: '',
      statut: 'Confidential',
      contexte: 'This firm, the link between insurers and policyholders when a claim occurs, wanted to redesign its "policyholder area", where customers track their ongoing claims. The aim of the application is to give policyholders more autonomy in following their case and in the steps required to move it forward. The appointment-booking journey is one of the major challenges of this redesign.',
      demarche: [
        { titre: 'Ergonomic audit', desc: 'Analysis of the existing product and identification of friction points in the current journey.' },
        { titre: 'Business workshops', desc: 'Workshops with business teams to understand the different stages of qualifying a claim.' },
        { titre: 'User research', desc: 'Interviews with end customers — the claimants — to understand their expectations and objectives.' },
        { titre: 'Mobile-first design', desc: 'Mobile-first ergonomic design of the screens, guaranteeing a responsive tool across every device.' },
        { titre: 'Testing & iteration', desc: 'User testing, iterations and visual design proposals.' },
      ],
      defis: [],
      resultats: [],
      competences: ['Ergonomic audit', 'Business workshops', 'User interviews', 'Mobile-first', 'Multi-device responsive', 'User testing', 'Visual design proposals'],
    },
  },
];

/* ══════════════════════════════════════════════════════════════════════
   AUTRES PROJETS — formats courts, présentés en cartes sur la page
   d'accueil. Même logique bilingue : bloc `en` optionnel par entrée.
   ══════════════════════════════════════════════════════════════════════ */
const AUTRES_PROJETS = [
  {
    id: 'odaia',
    image: 'Sources/annexe-book/autre-odaia.jpg',
    titre: 'Outil de détection assisté par IA',
    client: 'Éco-organisme du recyclage d\'électroménager',
    resume: 'Proposer aux opérateurs de tri un outil de détection assisté par intelligence artificielle, de la réponse à l\'appel d\'offres jusqu\'à l\'approbation des écrans en développement.',
    actions: [
      'Réalisation de la réponse à l\'appel d\'offres',
      'Cadrage du besoin et du scope',
      'Entretiens utilisateurs et experts',
      'Ateliers de parcours et de co-conception',
      'Conception des wireframes puis des maquettes',
      'Tests utilisateurs, suivi du développement et approbation des écrans',
    ],
    tags: ['Étude UX', 'Co-conception', 'Figma', 'Mobile', 'IA / Machine learning'],
    en: {
      titre: 'AI-assisted detection tool',
      client: 'Household appliance recycling organisation',
      resume: 'Giving sorting operators an AI-assisted detection tool, from the RFP response through to sign-off on screens during development.',
      actions: [
        'Writing the RFP response',
        'Scoping the need and the perimeter',
        'User and expert interviews',
        'Journey and co-design workshops',
        'Wireframes then final designs',
        'User testing, development follow-up and screen sign-off',
      ],
      tags: ['UX research', 'Co-design', 'Figma', 'Mobile', 'AI / Machine learning'],
    },
  },
  {
    id: 'sergic',
    image: 'Sources/annexe-book/autre-sergic.jpg',
    titre: 'Refonte d\'une application copropriétaires & locataires',
    client: 'Groupe de services immobiliers',
    resume: 'Refonte complète d\'une application destinée aux copropriétaires et aux locataires, sur toute la chaîne de valeur de la gestion immobilière.',
    actions: [
      'Ateliers de co-conception et de priorisation',
      'Maîtrise du budget',
      'Conception des wireframes et propositions de styles',
      'Conception des maquettes',
      'Amélioration de l\'arborescence',
      'Relation client, accompagnement et conseil sur les lois d\'ergonomie',
    ],
    tags: ['Étude UX', 'Co-conception', 'Figma', 'Mobile'],
    en: {
      titre: 'Redesign of a co-owner & tenant app',
      client: 'Property services group',
      resume: 'Complete redesign of an application for co-owners and tenants, covering the whole property management value chain.',
      actions: [
        'Co-design and prioritisation workshops',
        'Budget management',
        'Wireframes and visual style proposals',
        'Final designs',
        'Information architecture improvements',
        'Client relationship, guidance and advice on usability principles',
      ],
      tags: ['UX research', 'Co-design', 'Figma', 'Mobile'],
    },
  },
  {
    id: 'reassort',
    image: 'Sources/annexe-book/autre-reassort.jpg',
    titre: 'Outil de commande de réassort en magasin',
    client: 'Enseigne de distribution sportive',
    resume: 'Refonte des applications de commande — réassort, aubaines, portefeuille, stock et administration — pour fluidifier le parcours de commande des boutiques. L\'enjeu : passer de gros volumes sur plusieurs magasins simultanément, avec un maximum de lignes produit par page tout en restant lisible.',
    actions: [
      'Cadrage du scope et entretiens utilisateurs',
      'Ateliers avec les équipes métiers et commerciales pour comprendre les étapes de la commande',
      'Collaboration avec le Product Owner et les équipes de développement pour prioriser et concevoir un MVP',
      'Lotissement des conceptions UX/UI pour assurer la fluidité des développements',
    ],
    tags: ['Étude UX', 'Co-conception', 'Figma', 'Retail'],
    en: {
      titre: 'In-store replenishment ordering tool',
      client: 'Sports retail chain',
      resume: 'Redesign of the ordering applications — replenishment, deals, portfolio, stock and administration — to smooth the ordering journey for stores. The challenge: placing high-volume orders across several stores at once, with as many product lines per page as possible while staying readable.',
      actions: [
        'Scope framing and user interviews',
        'Workshops with business and sales teams to understand the ordering stages',
        'Collaboration with the Product Owner and dev teams to prioritise and design an MVP',
        'Phasing the UX/UI work to keep development flowing',
      ],
      tags: ['UX research', 'Co-design', 'Figma', 'Retail'],
    },
  },
  {
    id: 'extranet-fonds',
    image: 'Sources/annexe-book/autre-extranet.jpg',
    titre: 'Extranet biface partenaires & clients',
    client: 'Société de gestion de fonds immobiliers',
    resume: 'Refonte d\'un extranet biface, dédié aux partenaires et aux clients, pour accélérer la souscription en ligne réalisée par les conseillers — avec la création d\'une identité graphique dédiée.',
    actions: [
      'Collaboration avec une autre agence',
      'Arborescence du site et ateliers de co-conception',
      'Guide de style',
      'Lot 1 (produits, clients, patrimoine) : wireframes, maquettes, prototypes',
      'Lot 2 (souscription) : wireframes, maquettes, prototypes',
      'Lot 3 (dashboard, communauté, boîte à outils) : wireframes, maquettes, prototypes',
      'Tests utilisateurs et vérification des écrans pendant les sprints de développement',
    ],
    tags: ['Étude UX', 'Co-conception', 'Figma', 'Lots de conception', 'Finance'],
    en: {
      titre: 'Two-sided extranet for partners & clients',
      client: 'Real-estate fund management company',
      resume: 'Redesign of a two-sided extranet for partners and clients, to speed up the online subscription process carried out by advisers — including the creation of a dedicated visual identity.',
      actions: [
        'Collaboration with another agency',
        'Site information architecture and co-design workshops',
        'Style guide',
        'Batch 1 (products, clients, portfolio): wireframes, designs, prototypes',
        'Batch 2 (subscription): wireframes, designs, prototypes',
        'Batch 3 (dashboard, community, toolbox): wireframes, designs, prototypes',
        'User testing and screen review during development sprints',
      ],
      tags: ['UX research', 'Co-design', 'Figma', 'Phased design', 'Finance'],
    },
  },
];
