const PROJETS = [
  {
    id: 1,
    num: '01',
    titreCourt: 'Refonte d\'un parcours',
    sousTitreCourt: 'Optimisation du recrutement de partenaires pour une entreprise de transport de luxe',
    clientCourt: 'Transport de luxe',
    highlight: 'qualification',
    dureeCourte: '12 mois',
    kpis: [
      { titre: '90%', desc: 'Taux d\'occupation des véhicules de formation, contre 50 % auparavant' },
      { titre: '1 mois', desc: 'Délai de traitement d\'un dossier, de la création de compte à la signature du contrat' },
      { titre: 'Optimisé', desc: 'Taux de traitement des dossiers grâce à l\'optimisation des créneaux d\'entretien' },
    ],
    titre: 'Refonte du parcours d\'acquisition & qualification de partenaires',
    sousTitre: 'Optimisation du recrutement de partenaires pour une entreprise de transport de luxe',
    client: 'Entreprise de transport de luxe (secteur premium)',
    annee: '2025',
    type: 'Conception d\'une plateforme web dédiée — parcours d\'inscription et back-office de qualification',
    role: 'Product Designer (UX Research, UI Design, collaboration tech & PO)',
    duree: '12 mois — 7 mois de cadrage/conception + 5 mois de développement (10 sprints)',
    equipe: '1 Lead UX-UI · 1 UX · 1 UI · 1 PO · 1 Scrum Master · 2 Devs',
    outils: ['Mural', 'Figma', 'Loop'],
    statut: 'Confidentiel',
    competences: ['UX Research', 'Design System', 'Mobile-first', 'Prototypage', 'Éco-conception', 'Collaboration Agile', 'Accompagnement PO'],
    contexte: 'Le client souhaitait élargir sa flotte en recrutant de nouveaux partenaires de qualité, sans recourir à une plateforme ouverte comme ses concurrents. Le processus de qualification, entièrement manuel (mails, téléphone, vérifications documentaires), mobilisait fortement les équipes internes réparties en France et à l\'international, avec des critères hétérogènes selon les agences. Objectifs : fluidifier le travail des équipes de qualification, réduire les délais d\'inscription et adresser une cible en mobilité (mobile-first).',
    demarche: [
      { titre: 'Cadrage', desc: 'Définition des objectifs, ateliers de priorisation, choix techniques et interopérabilité avec l\'écosystème client, principes d\'éco-conception.' },
      { titre: 'Recherche utilisateur', desc: 'Interviews terrain ayant révélé les principales frustrations : vérification documentaire chronophage, gestion par mail, RDV de formation non honorés, disparité des process entre agences.' },
      { titre: 'Conception', desc: 'Benchmark concurrentiel, création d\'un design system, maquettage mobile-first, prototypage interactif et handoff développeurs.' },
      { titre: 'Accompagnement PO', desc: 'Co-rédaction du backlog, ateliers de priorisation MVP, découpage en 6 sprints (création de compte, qualification entreprise / chauffeurs / véhicules, entretiens, dashboard, gestion documentaire).' },
      { titre: 'Phase dev', desc: 'Validation des écrans à chaque sprint, itérations selon les contraintes techniques, échanges continus avec le lead tech.' },
    ],
    defis: [
      { titre: 'Méthodologie user-centric remise en question côté client', desc: 'Le MOA souhaitait écarter entretiens et ateliers pour imposer sa vision produit.', solution: 'Restructuration du planning et accompagnement du chef de projet pour impliquer les utilisateurs sous sa supervision : co-animation des entretiens et ateliers communs.' },
      { titre: 'Risque de ne pas atteindre l\'objectif d\'automatisation', desc: 'Le prestataire de vérification documentaire ne couvrait pas tous les besoins.', solution: 'Proposition d\'intégrer le pôle IA interne pour la vérification de conformité documentaire, validée en atelier technique après 4 mois de recherche.' },
      { titre: 'Aucune documentation héritée des projets précédents', desc: 'Deux projets antérieurs avaient été menés avec d\'autres équipes, sans design system ni guidelines.', solution: 'Création des fondations d\'un design system en m\'appuyant sur les projets existants et en collaboration avec le lead front, validé ensuite par le client sur les principes graphiques clés.' },
    ],
    resultats: [
      'Taux d\'occupation des véhicules de formation porté à 90 % (vs 50 % auparavant)',
      'Délai de traitement d\'un dossier ramené à 1 mois (de la création de compte à la signature du contrat)',
      'Augmentation du taux de traitement des dossiers grâce à l\'optimisation des créneaux d\'entretien',
    ],
    images: [
      { src: 'Sources/projets/refonte%20parcours/S6%20%E2%80%94%20Mon%20entreprise.png', type: 'mobile', alt: 'Tableau de bord partenaire' },
      {
        type: 'animated',
        alt: 'Parcours de création de compte',
        frames: [
          'Sources/projets/refonte%20parcours/animation/1.png',
          'Sources/projets/refonte%20parcours/animation/2.png',
          'Sources/projets/refonte%20parcours/animation/3.png',
          'Sources/projets/refonte%20parcours/animation/4.png',
        ],
      },
      { src: 'Sources/projets/refonte%20parcours/criteres.png', type: 'desktop', alt: 'Critères de qualification' },
    ],
    en: {
      titreCourt: 'Journey redesign',
      sousTitreCourt: 'Optimising partner recruitment for a luxury transport company',
      titre: 'Redesign of the partner acquisition & qualification journey',
      highlight: 'qualification',
      type: 'Web platform design — registration journey and qualification back-office',
      role: 'Product Designer (UX Research, UI Design, tech & PO collaboration)',
      dureeCourte: '12 months',
      statut: 'Confidential',
      contexte: 'The client wanted to expand their fleet by recruiting quality partners, without resorting to an open platform like their competitors. The qualification process, entirely manual (emails, phone calls, document checks), placed a heavy burden on internal teams spread across France and internationally, with inconsistent criteria between agencies. Objectives: streamline the work of qualification teams, reduce registration times, and address a mobile-first target audience.',
      demarche: [
        { titre: 'Scoping', desc: 'Defining objectives, prioritisation workshops, technical choices and interoperability with the client ecosystem, eco-design principles.' },
        { titre: 'User research', desc: 'Field interviews revealing the main frustrations: time-consuming document verification, email-based management, missed training appointments, inconsistent processes between agencies.' },
        { titre: 'Design', desc: 'Competitive benchmarking, design system creation, mobile-first wireframing, interactive prototyping and developer handoff.' },
        { titre: 'PO support', desc: 'Co-writing the backlog, MVP prioritisation workshops, breakdown into 6 sprints (account creation, company/driver/vehicle qualification, interviews, dashboard, document management).' },
        { titre: 'Dev phase', desc: 'Screen validation at each sprint, iterations based on technical constraints, ongoing exchanges with the tech lead.' },
      ],
      defis: [
        { titre: 'User-centric methodology challenged by the client', desc: 'The project owner wanted to bypass interviews and workshops to impose their own product vision.', solution: 'Restructured the schedule and coached the project manager to involve users under their supervision: co-facilitation of interviews and joint workshops.' },
        { titre: 'Risk of not achieving the automation objective', desc: 'The document verification provider did not cover all needs.', solution: 'Proposed integrating the internal AI team for document compliance verification, validated in a technical workshop after 4 months of research.' },
        { titre: 'No documentation from previous projects', desc: 'Two prior projects had been carried out by other teams, with no design system or guidelines.', solution: 'Created design system foundations based on existing projects and in collaboration with the front-end lead, subsequently validated by the client on key graphic principles.' },
      ],
      resultats: [
        'Training vehicle occupancy rate brought to 90% (vs 50% previously)',
        'File processing time reduced to 1 month (from account creation to contract signing)',
        'Increased file processing rate through optimised interview slot management',
      ],
      kpis: [
        { titre: '90%', desc: 'Training vehicle occupancy rate, vs 50% previously' },
        { titre: '1 month', desc: 'File processing time, from account creation to contract signing' },
        { titre: 'Optimised', desc: 'Increased file processing rate thanks to optimised interview slot management' },
      ],
      competences: ['UX Research', 'Design System', 'Mobile-first', 'Prototyping', 'Eco-design', 'Agile Collaboration', 'PO Support'],
    },
  },

  {
    id: 2,
    num: '02',
    titreCourt: 'Aéronautique & IA',
    sousTitreCourt: 'Aider les compagnies aériennes à diagnostiquer et réparer leurs pièces plus rapidement grâce à l\'IA',
    clientCourt: 'Constructeur aéronautique',
    highlight: 'détection',
    dureeCourte: '6 mois',
    kpis: [
      { titre: '190 K€', desc: 'Investissement débloqué pour poursuivre le projet et concevoir l\'ensemble des parcours' },
      { titre: 'POC validé', desc: 'Démonstration du potentiel financier du produit au client' },
      { titre: 'Phase 2', desc: 'Industrialisation de l\'outil planifiée à l\'issue du développement complet' },
    ],
    titre: 'POC d\'un outil de détection de dommages assisté par IA',
    sousTitre: 'Aider les compagnies aériennes à diagnostiquer et réparer leurs pièces plus rapidement grâce à l\'IA',
    client: 'Constructeur aéronautique',
    annee: '2025',
    type: 'Proof of Concept (POC) — outil métier intégrant IA et reconnaissance d\'image',
    role: 'Product Designer (UX Research, UI Design, collaboration avec l\'équipe IA)',
    duree: '6 mois',
    equipe: '1 Lead UX-UI · 1 UX · 1 UI · 1 PO · 1 Développeur IA',
    outils: ['Figma', 'Mural'],
    statut: 'Confidentiel',
    competences: ['UX Research', 'IA & Design', 'Co-conception', 'Prototypage haute fidélité', 'Design responsable', 'Collaboration multidisciplinaire'],
    contexte: 'Acteur majeur de la construction aéronautique, le client dispose d\'un référentiel riche de plusieurs milliers de cas de réparation, couvrant une grande diversité de pièces et de dommages. L\'objectif : rendre ses clients (compagnies aériennes) plus autonomes dans le diagnostic et la réparation de leurs pièces, en leur donnant un accès simplifié à ce référentiel. Un enjeu business critique, car un avion immobilisé en hangar représente un coût très élevé pour les compagnies. La promesse : réduire les délais de réparation et fluidifier le travail des techniciens sur le terrain.',
    demarche: [
      { titre: 'Cadrage', desc: 'Définition des objectifs du POC et alignement des parties prenantes.' },
      { titre: 'Recherche utilisateur', desc: 'Interviews terrain pour comprendre les processus métier, analyse du flow de réparation en hangar, observation de l\'environnement utilisateur (contraintes physiques, outils existants), identification des leviers d\'amélioration.' },
      { titre: 'Co-conception', desc: 'Ateliers pour assurer l\'interopérabilité avec les différents référentiels et processus de réparation existants.' },
      { titre: 'Ateliers IA', desc: '2 mois d\'immersion avec l\'équipe IA pour comprendre les mécaniques des référentiels et entraîner le modèle.' },
      { titre: 'Conception & prototypage', desc: 'Maquettage haute fidélité, prototypage interactif, tests utilisateurs et itérations conjointes design / IA. Bonnes pratiques IA appliquées : explicabilité, contrôle utilisateur, information factuelle sans biais ni fausse certitude.' },
    ],
    defis: [
      { titre: 'Complexité des référentiels métier multiples', desc: 'Plusieurs référentiels coexistaient avec des logiques propres, rendant difficile la conception d\'un parcours unifié.', solution: 'Organisation de 2 mois d\'ateliers dédiés avec l\'équipe IA pour cartographier les mécaniques et concevoir une expérience capable de s\'adapter à cette diversité.' },
      { titre: 'Intégration des bonnes pratiques IA dans une UX métier exigeante', desc: 'Risque que les techniciens en hangar rejettent les suggestions de l\'IA si elles paraissaient opaques ou erronées.', solution: 'Application de principes d\'IA responsable (explicabilité, possibilité d\'amender la réponse, pas de réponse présentée comme certaine) intégrés dès la conception des écrans.' },
    ],
    resultats: [
      'POC validé par le client, démontrant le potentiel financier du produit',
      'Investissement de 190 K€ débloqué par le constructeur pour poursuivre le projet et concevoir l\'ensemble des parcours',
      'Industrialisation de l\'outil planifiée à l\'issue du développement complet',
    ],
    en: {
      titreCourt: 'Aeronautics & AI',
      sousTitreCourt: 'Helping airlines diagnose and repair their parts faster with AI',
      titre: 'AI-assisted damage detection tool — POC',
      highlight: 'detection',
      type: 'Proof of Concept (POC) — professional tool integrating AI and image recognition',
      role: 'Product Designer (UX Research, UI Design, collaboration with AI team)',
      dureeCourte: '6 months',
      statut: 'Confidential',
      contexte: 'A major aircraft manufacturer holds a rich repository of several thousand repair cases, covering a wide variety of parts and damages. The goal: to make its clients (airlines) more autonomous in diagnosing and repairing their parts, by giving them simplified access to this repository. A critical business issue, as a grounded aircraft represents a very high cost for airlines. The promise: reduce repair times and streamline the work of field technicians.',
      demarche: [
        { titre: 'Scoping', desc: 'Defining the POC objectives and aligning stakeholders.' },
        { titre: 'User research', desc: 'Field interviews to understand business processes, analysis of the repair flow in the hangar, observation of the user environment (physical constraints, existing tools), identification of improvement levers.' },
        { titre: 'Co-design', desc: 'Workshops to ensure interoperability with the various existing repositories and repair processes.' },
        { titre: 'AI workshops', desc: '2 months of immersion with the AI team to understand the mechanics of the repositories and train the model.' },
        { titre: 'Design & prototyping', desc: 'High-fidelity wireframing, interactive prototyping, user testing and joint design/AI iterations. Responsible AI principles applied: explainability, user control, factual information without bias or false certainty.' },
      ],
      defis: [
        { titre: 'Complexity of multiple business repositories', desc: 'Several repositories coexisted with their own logic, making it difficult to design a unified journey.', solution: 'Organised 2 months of dedicated workshops with the AI team to map the mechanics and design an experience capable of adapting to this diversity.' },
        { titre: 'Integrating AI best practices into a demanding business UX', desc: 'Risk that hangar technicians would reject AI suggestions if they appeared opaque or incorrect.', solution: 'Application of responsible AI principles (explainability, ability to amend responses, no response presented as certain) integrated from the design phase.' },
      ],
      resultats: [
        'POC validated by the client, demonstrating the financial potential of the product',
        '€190K investment unlocked by the manufacturer to continue the project and design the complete journeys',
        'Tool industrialisation planned upon completion of full development',
      ],
      kpis: [
        { titre: '€190K', desc: 'Investment unlocked to continue the project and design all journeys' },
        { titre: 'POC validated', desc: 'Demonstrating the product\'s financial potential to the client' },
        { titre: 'Phase 2', desc: 'Tool industrialisation planned upon completion of full development' },
      ],
      competences: ['UX Research', 'AI & Design', 'Co-design', 'High-fidelity Prototyping', 'Responsible Design', 'Multidisciplinary Collaboration'],
    },
  },

  {
    id: 3,
    num: '03',
    titreCourt: 'Simulateur financier',
    sousTitreCourt: 'Conception du MVP d\'un simulateur financier pour des projets de recherche, après une réponse d\'appel d\'offre',
    clientCourt: 'SATT',
    highlight: 'simulation',
    dureeCourte: '6 mois',
    kpis: [
      { titre: 'MVP', desc: 'Livraison prévue le 30 mai 2026' },
      { titre: 'Accéléré', desc: 'Méthodologie de conception grâce au design system Telerik et au générateur d\'interface' },
      { titre: 'Validé', desc: 'Validation continue du client à chaque étape (cadrage, design, sprints)' },
    ],
    titre: 'Plateforme de simulation financière pour projets de recherche',
    sousTitre: 'Conception du MVP suite au gain de l\'appel d\'offre',
    client: 'SATT (Société d\'Accélération du Transfert de Technologies)',
    annee: '2025 — 2026',
    type: 'Conception et développement d\'un MVP — plateforme web métier multi-utilisateurs',
    role: 'Product Designer (UX Research, UI Design, collaboration tech & PO)',
    duree: '6 mois (réponse à l\'AO juillet 2025 · gain septembre 2025 · sprints du 1er décembre 2025 au 30 mai 2026)',
    equipe: '1 Lead UX-UI · 1 UX · 1 UI · 1 PO · 1 Dev Front · 1 Dev Back',
    outils: ['Figma', 'Mural'],
    statut: 'Confidentiel',
    competences: ['UX Research', 'Design System', 'Conception métier', 'Accompagnement PO', 'Collaboration Agile', 'Adaptation multi-profils utilisateurs'],
    contexte: 'La SATT porte une plateforme destinée à faciliter la conduite de projets de recherche partagés entre entreprises et universités. L\'enjeu : adresser des profils utilisateurs très hétérogènes — scientifiques et chercheurs expérimentés, services de financement en charge des décisions, mais aussi utilisateurs moins familiers du sujet. La plateforme doit donc proposer un outil expert pour les profils aguerris et rester accessible à des utilisateurs novices en matière de financement public ou privé.',
    demarche: [
      { titre: 'Cadrage', desc: 'Réalisé pendant la phase d\'appel d\'offre via plusieurs échanges avec le client, permettant d\'affiner sa vision et d\'identifier les enjeux clés du MVP.' },
      { titre: 'Recherche utilisateur', desc: '1 interview par typologie d\'utilisateur, ayant permis de corriger plusieurs flows définis dans le CDC qui ne reflétaient pas la réalité terrain.' },
      { titre: 'Parcours utilisateurs', desc: 'Formalisation des différents parcours à partir des enseignements des interviews.' },
      { titre: 'Conception', desc: 'Interface de formulaire pas-à-pas (proposée et validée dès l\'appel d\'offre), conçue à partir du design system Telerik pour exploiter un générateur d\'interface — choix qui a permis d\'accélérer significativement la phase de conception, de design et de développement.' },
      { titre: 'Phase dev', desc: 'Validation des écrans à chaque sprint, itérations selon les contraintes techniques, échanges continus avec l\'équipe de développement.' },
    ],
    defis: [
      { titre: 'Un Product Owner côté client sans expérience préalable dans ce rôle', desc: 'Le PO client manquait de temps et de culture agile pour structurer un backlog exploitable.', solution: 'Mise en place d\'un PO interne en accompagnement, et animation d\'ateliers dédiés (Product Vision, Roadmap, priorisation des sprints) pour structurer le pilotage produit.' },
      { titre: 'Un métier technique complexe (calculs financiers spécifiques)', desc: 'La phase d\'acculturation a pris du temps pour l\'ensemble de l\'équipe.', solution: 'Mutualisation des connaissances acquises tout au long du projet et restitution structurée aux développeurs pour leur donner une vision métier claire et partagée.' },
    ],
    resultats: [
      'MVP en cours — livraison prévue le 30/05/2026',
      'Méthodologie de conception accélérée grâce au choix du design system Telerik et du générateur d\'interface',
      'Validation continue du client à chaque étape (cadrage, design, sprints)',
    ],
    images: [
      { src: 'Sources/projets/simulateur%20financier/annexlabe%20simulation%201%201.png', type: 'desktop', alt: 'Liste des simulations' },
      { src: 'Sources/projets/simulateur%20financier/annexlabe%20simulation%202%201.png', type: 'desktop', alt: 'Formulaire de simulation' },
    ],
    en: {
      titreCourt: 'Financial simulator',
      sousTitreCourt: 'Designing the MVP of a financial simulator for research projects, following an RFP response',
      titre: 'Financial simulation platform for research projects',
      highlight: 'simulation',
      type: 'MVP design and development — multi-user professional web platform',
      role: 'Product Designer (UX Research, UI Design, tech & PO collaboration)',
      dureeCourte: '6 months',
      statut: 'Confidential',
      contexte: 'The SATT supports a platform designed to facilitate the management of shared research projects between companies and universities. The challenge: addressing very diverse user profiles — experienced scientists and researchers, finance teams in charge of decisions, and users less familiar with the subject. The platform must therefore offer an expert tool for experienced profiles while remaining accessible to users unfamiliar with public or private funding.',
      demarche: [
        { titre: 'Scoping', desc: 'Conducted during the RFP phase through several exchanges with the client, refining their vision and identifying key MVP challenges.' },
        { titre: 'User research', desc: '1 interview per user type, which corrected several flows defined in the specifications that did not reflect field reality.' },
        { titre: 'User journeys', desc: 'Formalising the different journeys based on insights from interviews.' },
        { titre: 'Design', desc: 'Step-by-step form interface (proposed and validated during the RFP), designed using the Telerik design system to leverage an interface generator — a choice that significantly accelerated the design and development phases.' },
        { titre: 'Dev phase', desc: 'Screen validation at each sprint, iterations based on technical constraints, ongoing exchanges with the development team.' },
      ],
      defis: [
        { titre: 'A client-side Product Owner with no prior experience in the role', desc: 'The client PO lacked time and agile culture to structure a workable backlog.', solution: 'Set up an internal supporting PO, and facilitated dedicated workshops (Product Vision, Roadmap, sprint prioritisation) to structure product management.' },
        { titre: 'A complex technical domain (specific financial calculations)', desc: 'The onboarding phase took time for the entire team.', solution: 'Pooled knowledge acquired throughout the project and structured restitution to developers to give them a clear, shared business understanding.' },
      ],
      resultats: [
        'MVP in progress — delivery scheduled for 30/05/2026',
        'Accelerated design methodology thanks to the Telerik design system and interface generator',
        'Continuous client validation at each stage (scoping, design, sprints)',
      ],
      kpis: [
        { titre: 'MVP', desc: 'Delivery scheduled for 30 May 2026' },
        { titre: 'Accelerated', desc: 'Design methodology accelerated thanks to the Telerik design system and interface generator' },
        { titre: 'Validated', desc: 'Continuous client validation at each stage (scoping, design, sprints)' },
      ],
      competences: ['UX Research', 'Design System', 'Business Design', 'PO Support', 'Agile Collaboration', 'Multi-profile User Adaptation'],
    },
  },

  {
    id: 4,
    num: '04',
    titreCourt: 'Design System',
    sousTitreCourt: 'Création from scratch du design system d\'une entreprise multi-marque',
    clientCourt: 'Entreprise multi-marque',
    highlight: 'Design System',
    dureeCourte: '1 an et 6 mois',
    kpis: [
      { titre: '38', desc: 'Composants livrés avec leurs variants et leur double documentation' },
      { titre: 'Adopté', desc: 'Forte adoption par les équipes design et développement' },
      { titre: 'Unifié', desc: 'Cohérence visuelle assurée entre les différentes marques et outils de l\'écosystème' },
    ],
    titre: 'Conception d\'un Design System multi-marque',
    sousTitre: 'Création from scratch du design system d\'une entreprise multi-marque',
    client: 'Entreprise multi-marque',
    annee: '2024 — 2025',
    type: 'Création d\'un Design System scalable — composants React et Angular, documentation design & dev',
    role: 'Designer (analyse technique, recherche d\'usage, conception des composants)',
    duree: '1 an et 6 mois',
    equipe: '1 Lead UX-UI · 1 Designer · 1 Tech Lead · 1 Développeur',
    outils: ['Figma', 'Telerik', 'Mural', 'Zeplin', 'Azure'],
    statut: 'Confidentiel',
    competences: ['Design System', 'Conception de composants', 'Documentation design & dev', 'Collaboration tech', 'Material Design', 'Multi-framework (React / Angular)', 'Figma branching'],
    contexte: 'Une entreprise multi-marque souhaitait se doter d\'un Design System unifié, capable de s\'adapter sans friction à l\'identité de chacune de ses marques. L\'objectif : accélérer les développements futurs, garantir la cohérence visuelle entre les différents outils et marques, et poser des fondations techniques solides pour l\'écosystème produit.',
    demarche: [
      { titre: 'Inspiration & cadrage', desc: 'Design system pensé dans l\'esprit du Material Design, adapté aux contraintes multi-marque.' },
      { titre: 'Organisation projet', desc: 'Design sprints parallélisés avec les sprints de développement, cérémonies communes entre les deux équipes pour assurer un alignement continu.' },
      { titre: 'Répartition design', desc: 'Tâches de conception réparties entre les deux designers, avec utilisation du système de branches Figma pour itérer sans casser les composants déjà validés.' },
      { titre: 'Conception', desc: 'Analyse technique conjointe avec l\'équipe dev pour garantir l\'adaptabilité des composants à différents langages (React, Angular), technologies et supports.' },
      { titre: 'Livrable final', desc: '38 composants intégrant l\'ensemble de leurs variants, accompagnés d\'une double documentation : l\'une pour les designers, l\'autre pour les développeurs.' },
    ],
    defis: [
      { titre: 'Complexité technique multi-environnement', desc: 'Conception de composants suffisamment flexibles pour fonctionner sur plusieurs frameworks (React, Angular), supports et identités de marque, sans dégradation de cohérence.', solution: 'Travail rapproché et continu avec l\'équipe technique dès la phase de conception, intégration des contraintes dev en amont du design, et validation systématique de la faisabilité de chaque composant avant industrialisation.' },
    ],
    resultats: [
      '38 composants livrés avec leurs variants et leur double documentation',
      'Temps de développement réduit sur les nouveaux projets grâce à la réutilisation des composants',
      'Forte adoption par les équipes design et développement',
      'Cohérence visuelle assurée entre les différentes marques et outils de l\'écosystème',
    ],
    images: [
      { src: 'Sources/projets/Design%20System/image%202.png', type: 'full',    alt: 'Documentation couleurs & typographie' },
      { src: 'Sources/projets/Design%20System/image%201.png', type: 'desktop', alt: 'Vue composants — Figma' },
      { src: 'Sources/projets/Design%20System/image%203.png', type: 'desktop', alt: 'Panel variables — tokens de couleur' },
    ],
    en: {
      titreCourt: 'Design System',
      sousTitreCourt: 'Creating a multi-brand Design System from scratch',
      titre: 'Multi-brand Design System design',
      highlight: 'Design System',
      type: 'Scalable Design System — React and Angular components, design & dev documentation',
      role: 'Designer (technical analysis, usage research, component design)',
      dureeCourte: '1 year and 6 months',
      statut: 'Confidential',
      contexte: 'A multi-brand company wanted to equip itself with a unified Design System, capable of adapting seamlessly to each brand\'s identity. The objective: accelerate future developments, ensure visual consistency across the various tools and brands, and lay solid technical foundations for the product ecosystem.',
      demarche: [
        { titre: 'Inspiration & scoping', desc: 'Design system conceived in the spirit of Material Design, adapted to multi-brand constraints.' },
        { titre: 'Project organisation', desc: 'Design sprints parallelised with development sprints, joint ceremonies between both teams to ensure ongoing alignment.' },
        { titre: 'Design distribution', desc: 'Tasks distributed between the two designers, using the Figma branching system to iterate without breaking already-validated components.' },
        { titre: 'Design', desc: 'Joint technical analysis with the dev team to ensure component adaptability across different languages (React, Angular), technologies and platforms.' },
        { titre: 'Final deliverable', desc: '38 components including all their variants, accompanied by dual documentation: one for designers, the other for developers.' },
      ],
      defis: [
        { titre: 'Multi-environment technical complexity', desc: 'Designing components flexible enough to work across multiple frameworks (React, Angular), platforms and brand identities, without degrading consistency.', solution: 'Close and ongoing collaboration with the technical team from the design phase, integrating dev constraints upstream, and systematic feasibility validation of each component before industrialisation.' },
      ],
      resultats: [
        '38 components delivered with their variants and dual documentation',
        'Reduced development time on new projects thanks to component reuse',
        'Strong adoption by design and development teams',
        'Visual consistency ensured across the various brands and tools in the ecosystem',
      ],
      kpis: [
        { titre: '38', desc: 'Components delivered with their variants and dual documentation' },
        { titre: 'Adopted', desc: 'Strong adoption by design and development teams' },
        { titre: 'Unified', desc: 'Visual consistency ensured across different brands and ecosystem tools' },
      ],
      competences: ['Design System', 'Component Design', 'Design & Dev Documentation', 'Tech Collaboration', 'Material Design', 'Multi-framework (React / Angular)', 'Figma Branching'],
    },
  },
];
